language: java
jdk:
- oraclejdk8

sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  matrix:
  - TERM=dumb
  global:

install: "./gradlew --version"

script: ./gradlew --continue build test aggregateJavadoc publishGhPages artifactoryPublish -PgithubUser="${GITHUB_TOKEN}" -PgithubPassword="" -PjfrogUser="${JFROG_USER}" -PjfrogPassword="${JFROG_PASSWORD}" --stacktrace
